#For Kanayama
Kx: 0
Ky: 0.05
Kw: 0.07

#Car Specification
max_vel: 6.38 #Equal to 23km/h
min_vel: 0.1
max_steer: 0.349 #Equal to +- 20 degree
min_steer: -0.349
L: 1.023 #Car length b/w wheels

#Debugging Output
debug_console_output: True